name: Sync Repositories

on:
  push:
    branches:
      - master  # Change to your default branch name

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository B
        uses: actions/checkout@v2

      - name: Sync with Repository A
        run: |
          git remote add upstream https://github.com/venkatsai8/dummy.git
