name: Sync Repository A to Repository B

on:
 push:
 repository_dispatch:
    types:
      - features

jobs:
 sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository A
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Checkout Repository B
      uses: actions/checkout@v2
      with:
        repository: venkatsai8/dest-repo-b.git
        ref: feature
        path: dest-repo-b

    - name: Fetch Changes from Repository A
      run: |
        echo "changing to directory of dest repo"
        cd dest-repo-b
        git config pull.rebase false
        echo "Changing to feature branch"
        git checkout feature
        echo "Checking remote version first"
        git remote -v
        echo "fetching the origin first"
        git fetch origin
        echo "checking username and email"
        git config --global user.email "natrajsai7@gmail.com"
        git config --global user.name "venkatsai8"
        git config --global --list
        echo "Adding the source remote repo"
        git remote add source https://github.com/venkatsai8/source-repo-a.git
        echo "Again checking the remote version"
        git remote -v
        echo "Fetchig the source data first of soruce repo"
        git fetch source
        echo "Now pulling the features source branch from source"
        git pull source features --allow-unrelated-histories
        git cherry-pick -m 1 HEAD
        
    - name : Applying changes to B
      run: |
        echo "Now pushing it"
        git push origin feature 

    - name: Push Changes to Repository B
      uses: actions/checkout@v2
      with:
        repository: venkatsai8/dest-repo-b.git
        ref: feature
        token: ${{ secrets.GHTOKEN }}
