name: Update B repo from A repo

on:
  push:
    branches:
      - master

jobs:
  source-repo-a:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'https://{classic_token_natraj}@github.com/venkatsai8/source-repo-a'
          token: ${{ secrets.GITHUB_TOKEN }}
