name: Sync Repository A to Repository B

on:
 push:
    branches:
      - feature

jobs:
 sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository A
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Checkout Repository B
      uses: actions/checkout@v2
      with:
        repository: venkatsai8/dest-repo-b.git
        ref: feature
        path: dest-repo-b

    - name: Fetch Changes from Repository A
      run: |
        cd dest-repo-b
        git checkout feature
        git config --global user.email "natrajsai7@gmail.com"
        git config --global user.name "venkatsai8"
        git remote add source https://github.com/venkatsai8/source-repo-a.git
        git remote -v
        git fetch source
        git pull source features
        

    - name: Apply Changes to Repository B
      run: |
        git cherry-pick HEAD
        git push origin feature

    - name: Push Changes to Repository B
      uses: actions/checkout@v2
      with:
        repository: venkatsai8/dest-repo-b.git
        ref: feature
        token: ${{ secrets.GHTOKEN }}
